import type { Metadata } from "next";
import "./main.scss";
import { ConfigProvider, ConfigProviderProps } from "antd";
import { ConfigOptions } from "antd/es/message/interface";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const COLORS = {
  background: 'var(--background)',
  foreground: 'var(--foreground)',
  hover: 'var(--hover)',
  active: 'var(--active)',
  activeElement: 'var(--active-element)',
  // --text-color: var(--color-gray-500),
  // --hover: theme('colors.blue.400'),
  // --active: theme('colors.blue.600'),
  // --activeElement: theme('colors.blue.200'),
}

const token: ConfigProviderProps['theme'] = {
  token: {
  },

  components: {
    Layout: {
      headerBg: COLORS.foreground
    },

    Menu: {
      colorBgBase: COLORS.foreground,
      itemBg: COLORS.foreground,
      colorSplit: COLORS.foreground,
      itemHoverColor: COLORS.hover,
      itemSelectedColor: COLORS.active,
      motionDurationSlow: '0.1s',
      // horizontalItemHoverColor: 'red',
      // horizontalItemHoverBg: 'black',
      colorLinkHover: 'black',
      horizontalItemSelectedColor: COLORS.active,
      horizontalItemHoverColor: COLORS.hover,

      
      // horizontalItemHoverColor: COLORS.hover,
      // motionDurationFast: 'fast',

      // colorBgBase: 
    }
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <ConfigProvider
      theme={token}>
        <body className="min-h-full flex flex-col">
          {children}
        </body>
      </ConfigProvider>
    </html>
  );
}
