export { type ICatergory } from './ICategory'
export { type ITypeOperation } from '../../../entities/OperationType/lib/OpertionTypeTypes' 
export { type IDepartment } from './IDepartment'
export { type IEquipment } from './IEquipment'
export { type MakeOptional } from './MakeOptional'